name: Deploy to WordPress.org

on:
  push:
    branches:
      - github-action-to-deploy-on-wordpress
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy (e.g., 1.2.3)'
        required: true
        type: string

jobs:
  deploy:
    name: Deploy to WordPress.org SVN
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Install all dependencies
        run: |
          composer install --optimize-autoloader

      - name: Get version from release or input
        id: version
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            VERSION="${{ github.event.release.tag_name }}"
          elif [ "${{ github.event_name }}" == "push" ]; then
            VERSION="v7.2.0"
          else
            VERSION="${{ github.event.inputs.version }}"
          fi
          # Remove 'v' prefix if present
          VERSION=${VERSION#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Deploying version: $VERSION"

      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
          dry-run: true
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: talentlms
          VERSION: ${{ steps.version.outputs.version }}

      - name: Upload plugin ZIP as artifact
        uses: actions/upload-artifact@v4
        with:
          name: talentlms-${{ steps.version.outputs.version }}
          path: ${{ steps.deploy.outputs.zip-path }}
          retention-days: 30



